# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_supplier_arrears.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SupplierArrears(object):
    def setupUi(self, SupplierArrears):
        SupplierArrears.setObjectName("SupplierArrears")
        SupplierArrears.resize(953, 603)
        self.verticalLayout = QtWidgets.QVBoxLayout(SupplierArrears)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(SupplierArrears)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.summary_table = QtWidgets.QTableView(SupplierArrears)
        self.summary_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.summary_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.summary_table.setObjectName("summary_table")
        self.summary_table.verticalHeader().setVisible(True)
        self.verticalLayout.addWidget(self.summary_table)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(SupplierArrears)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.detail_table = QtWidgets.QTableWidget(SupplierArrears)
        self.detail_table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.detail_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.detail_table.setObjectName("detail_table")
        self.detail_table.setColumnCount(0)
        self.detail_table.setRowCount(0)
        self.detail_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.detail_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SupplierArrears)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(SupplierArrears)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.summary_need_pay = QtWidgets.QLabel(SupplierArrears)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.summary_need_pay.setFont(font)
        self.summary_need_pay.setObjectName("summary_need_pay")
        self.horizontalLayout.addWidget(self.summary_need_pay)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.single_button = QtWidgets.QPushButton(SupplierArrears)
        self.single_button.setObjectName("single_button")
        self.horizontalLayout.addWidget(self.single_button)
        self.bulk_button = QtWidgets.QPushButton(SupplierArrears)
        self.bulk_button.setObjectName("bulk_button")
        self.horizontalLayout.addWidget(self.bulk_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SupplierArrears)
        QtCore.QMetaObject.connectSlotsByName(SupplierArrears)

    def retranslateUi(self, SupplierArrears):
        _translate = QtCore.QCoreApplication.translate
        SupplierArrears.setWindowTitle(_translate("SupplierArrears", "Form"))
        self.label_3.setText(_translate("SupplierArrears", "供应商欠款汇总"))
        self.label_4.setText(_translate("SupplierArrears", "供应商欠款明细"))
        self.detail_table.setSortingEnabled(False)
        self.label.setText(_translate("SupplierArrears", "已选合计金额："))
        self.label_2.setText(_translate("SupplierArrears", "￥"))
        self.summary_need_pay.setText(_translate("SupplierArrears", "0.00"))
        self.single_button.setText(_translate("SupplierArrears", "单个付款"))
        self.bulk_button.setText(_translate("SupplierArrears", "批量付款"))

