# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_supplier_arrears.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SupplierArrears(object):
    def setupUi(self, SupplierArrears):
        SupplierArrears.setObjectName("SupplierArrears")
        SupplierArrears.resize(953, 603)
        self.verticalLayout = QtWidgets.QVBoxLayout(SupplierArrears)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(SupplierArrears)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.summary_table = QtWidgets.QTableView(SupplierArrears)
        self.summary_table.setObjectName("summary_table")
        self.verticalLayout.addWidget(self.summary_table)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(SupplierArrears)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.detail_table = QtWidgets.QTableWidget(SupplierArrears)
        self.detail_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.detail_table.setObjectName("detail_table")
        self.detail_table.setColumnCount(4)
        self.detail_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.detail_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detail_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.detail_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detail_table.setHorizontalHeaderItem(3, item)
        self.detail_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.detail_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SupplierArrears)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(SupplierArrears)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.single_button = QtWidgets.QPushButton(SupplierArrears)
        self.single_button.setObjectName("single_button")
        self.horizontalLayout.addWidget(self.single_button)
        self.bulk_button = QtWidgets.QPushButton(SupplierArrears)
        self.bulk_button.setObjectName("bulk_button")
        self.horizontalLayout.addWidget(self.bulk_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SupplierArrears)
        QtCore.QMetaObject.connectSlotsByName(SupplierArrears)

    def retranslateUi(self, SupplierArrears):
        _translate = QtCore.QCoreApplication.translate
        SupplierArrears.setWindowTitle(_translate("SupplierArrears", "Form"))
        self.label_3.setText(_translate("SupplierArrears", "供应商欠款汇总"))
        self.label_4.setText(_translate("SupplierArrears", "供应商欠款明细"))
        self.detail_table.setSortingEnabled(True)
        item = self.detail_table.horizontalHeaderItem(0)
        item.setText(_translate("SupplierArrears", "序号"))
        item = self.detail_table.horizontalHeaderItem(1)
        item.setText(_translate("SupplierArrears", "供应商"))
        item = self.detail_table.horizontalHeaderItem(2)
        item.setText(_translate("SupplierArrears", "欠款金额"))
        item = self.detail_table.horizontalHeaderItem(3)
        item.setText(_translate("SupplierArrears", "操作"))
        self.label.setText(_translate("SupplierArrears", "已选合计金额："))
        self.label_2.setText(_translate("SupplierArrears", "2100000"))
        self.single_button.setText(_translate("SupplierArrears", "单个付款"))
        self.bulk_button.setText(_translate("SupplierArrears", "批量付款"))

