# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 692)
        MainWindow.setMinimumSize(QtCore.QSize(989, 692))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(50, 50))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.comboBox = QtWidgets.QComboBox(self.tab_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(86, 20))
        self.comboBox.setMaximumSize(QtCore.QSize(86, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox)
        self.dateEdit_5 = QtWidgets.QDateEdit(self.tab_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_5.sizePolicy().hasHeightForWidth())
        self.dateEdit_5.setSizePolicy(sizePolicy)
        self.dateEdit_5.setMinimumSize(QtCore.QSize(88, 25))
        self.dateEdit_5.setMaximumSize(QtCore.QSize(88, 25))
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.horizontalLayout_18.addWidget(self.dateEdit_5)
        self.label_10 = QtWidgets.QLabel(self.tab_15)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_18.addWidget(self.label_10)
        self.dateEdit_6 = QtWidgets.QDateEdit(self.tab_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_6.sizePolicy().hasHeightForWidth())
        self.dateEdit_6.setSizePolicy(sizePolicy)
        self.dateEdit_6.setMinimumSize(QtCore.QSize(88, 25))
        self.dateEdit_6.setMaximumSize(QtCore.QSize(88, 25))
        self.dateEdit_6.setObjectName("dateEdit_6")
        self.horizontalLayout_18.addWidget(self.dateEdit_6)
        self.xiaofeiCheck = QtWidgets.QPushButton(self.tab_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xiaofeiCheck.sizePolicy().hasHeightForWidth())
        self.xiaofeiCheck.setSizePolicy(sizePolicy)
        self.xiaofeiCheck.setMinimumSize(QtCore.QSize(86, 25))
        self.xiaofeiCheck.setMaximumSize(QtCore.QSize(86, 25))
        self.xiaofeiCheck.setObjectName("xiaofeiCheck")
        self.horizontalLayout_18.addWidget(self.xiaofeiCheck)
        self.xiaofeiOut = QtWidgets.QPushButton(self.tab_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xiaofeiOut.sizePolicy().hasHeightForWidth())
        self.xiaofeiOut.setSizePolicy(sizePolicy)
        self.xiaofeiOut.setMinimumSize(QtCore.QSize(85, 25))
        self.xiaofeiOut.setMaximumSize(QtCore.QSize(86, 25))
        self.xiaofeiOut.setObjectName("xiaofeiOut")
        self.horizontalLayout_18.addWidget(self.xiaofeiOut)
        self.xiaofeiIn = QtWidgets.QPushButton(self.tab_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xiaofeiIn.sizePolicy().hasHeightForWidth())
        self.xiaofeiIn.setSizePolicy(sizePolicy)
        self.xiaofeiIn.setMinimumSize(QtCore.QSize(85, 25))
        self.xiaofeiIn.setMaximumSize(QtCore.QSize(86, 25))
        self.xiaofeiIn.setObjectName("xiaofeiIn")
        self.horizontalLayout_18.addWidget(self.xiaofeiIn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem3)
        self.verticalLayout_27.addLayout(self.horizontalLayout_18)
        self.xiaofeiTable = QtWidgets.QTableView(self.tab_15)
        self.xiaofeiTable.setMinimumSize(QtCore.QSize(941, 564))
        self.xiaofeiTable.setObjectName("xiaofeiTable")
        self.verticalLayout_27.addWidget(self.xiaofeiTable)
        self.verticalLayout_26.addLayout(self.verticalLayout_27)
        self.label_11 = QtWidgets.QLabel(self.tab_15)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_26.addWidget(self.label_11)
        self.verticalLayout_3.addLayout(self.verticalLayout_26)
        self.tabWidget.addTab(self.tab_15, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.mendianMenu1 = QtWidgets.QTableView(self.tab)
        self.mendianMenu1.setMinimumSize(QtCore.QSize(271, 489))
        self.mendianMenu1.setObjectName("mendianMenu1")
        self.verticalLayout_7.addWidget(self.mendianMenu1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu1Add = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu1Add.sizePolicy().hasHeightForWidth())
        self.menu1Add.setSizePolicy(sizePolicy)
        self.menu1Add.setMinimumSize(QtCore.QSize(79, 42))
        self.menu1Add.setMaximumSize(QtCore.QSize(79, 42))
        self.menu1Add.setObjectName("menu1Add")
        self.horizontalLayout.addWidget(self.menu1Add)
        self.menu1Update = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu1Update.sizePolicy().hasHeightForWidth())
        self.menu1Update.setSizePolicy(sizePolicy)
        self.menu1Update.setMinimumSize(QtCore.QSize(79, 42))
        self.menu1Update.setMaximumSize(QtCore.QSize(79, 42))
        self.menu1Update.setObjectName("menu1Update")
        self.horizontalLayout.addWidget(self.menu1Update)
        self.menu1Remove = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu1Remove.sizePolicy().hasHeightForWidth())
        self.menu1Remove.setSizePolicy(sizePolicy)
        self.menu1Remove.setMinimumSize(QtCore.QSize(79, 42))
        self.menu1Remove.setMaximumSize(QtCore.QSize(79, 42))
        self.menu1Remove.setObjectName("menu1Remove")
        self.horizontalLayout.addWidget(self.menu1Remove)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mendianMenu2 = QtWidgets.QTableView(self.tab)
        self.mendianMenu2.setMinimumSize(QtCore.QSize(531, 491))
        self.mendianMenu2.setObjectName("mendianMenu2")
        self.horizontalLayout_3.addWidget(self.mendianMenu2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_10.setObjectName("checkBox_10")
        self.verticalLayout.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout.addWidget(self.checkBox_11)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.menu2Add = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu2Add.sizePolicy().hasHeightForWidth())
        self.menu2Add.setSizePolicy(sizePolicy)
        self.menu2Add.setMinimumSize(QtCore.QSize(75, 39))
        self.menu2Add.setMaximumSize(QtCore.QSize(75, 39))
        self.menu2Add.setObjectName("menu2Add")
        self.horizontalLayout_2.addWidget(self.menu2Add)
        self.menu2Update = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu2Update.sizePolicy().hasHeightForWidth())
        self.menu2Update.setSizePolicy(sizePolicy)
        self.menu2Update.setMinimumSize(QtCore.QSize(75, 39))
        self.menu2Update.setMaximumSize(QtCore.QSize(75, 39))
        self.menu2Update.setObjectName("menu2Update")
        self.horizontalLayout_2.addWidget(self.menu2Update)
        self.menu2Remove = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu2Remove.sizePolicy().hasHeightForWidth())
        self.menu2Remove.setSizePolicy(sizePolicy)
        self.menu2Remove.setMinimumSize(QtCore.QSize(75, 39))
        self.menu2Remove.setMaximumSize(QtCore.QSize(75, 39))
        self.menu2Remove.setObjectName("menu2Remove")
        self.horizontalLayout_2.addWidget(self.menu2Remove)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.userAdd = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userAdd.sizePolicy().hasHeightForWidth())
        self.userAdd.setSizePolicy(sizePolicy)
        self.userAdd.setMinimumSize(QtCore.QSize(105, 39))
        self.userAdd.setMaximumSize(QtCore.QSize(105, 39))
        self.userAdd.setObjectName("userAdd")
        self.horizontalLayout_4.addWidget(self.userAdd)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.UserTable = QtWidgets.QTableView(self.tab_2)
        self.UserTable.setMinimumSize(QtCore.QSize(940, 491))
        self.UserTable.setObjectName("UserTable")
        self.verticalLayout_5.addWidget(self.UserTable)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.deleteWorker = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteWorker.sizePolicy().hasHeightForWidth())
        self.deleteWorker.setSizePolicy(sizePolicy)
        self.deleteWorker.setMinimumSize(QtCore.QSize(127, 59))
        self.deleteWorker.setMaximumSize(QtCore.QSize(127, 59))
        self.deleteWorker.setObjectName("deleteWorker")
        self.horizontalLayout_13.addWidget(self.deleteWorker)
        self.updateWorker = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateWorker.sizePolicy().hasHeightForWidth())
        self.updateWorker.setSizePolicy(sizePolicy)
        self.updateWorker.setMinimumSize(QtCore.QSize(126, 59))
        self.updateWorker.setMaximumSize(QtCore.QSize(126, 59))
        self.updateWorker.setObjectName("updateWorker")
        self.horizontalLayout_13.addWidget(self.updateWorker)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.verticalLayout_12.addLayout(self.verticalLayout_5)
        self.verticalLayout_23.addLayout(self.verticalLayout_12)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.UserTable_2 = QtWidgets.QTableView(self.tab_3)
        self.UserTable_2.setMinimumSize(QtCore.QSize(940, 541))
        self.UserTable_2.setObjectName("UserTable_2")
        self.verticalLayout_20.addWidget(self.UserTable_2)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.addUser = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addUser.sizePolicy().hasHeightForWidth())
        self.addUser.setSizePolicy(sizePolicy)
        self.addUser.setMinimumSize(QtCore.QSize(75, 58))
        self.addUser.setMaximumSize(QtCore.QSize(75, 58))
        self.addUser.setObjectName("addUser")
        self.horizontalLayout_19.addWidget(self.addUser)
        self.changeUser = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changeUser.sizePolicy().hasHeightForWidth())
        self.changeUser.setSizePolicy(sizePolicy)
        self.changeUser.setMinimumSize(QtCore.QSize(75, 58))
        self.changeUser.setMaximumSize(QtCore.QSize(75, 58))
        self.changeUser.setObjectName("changeUser")
        self.horizontalLayout_19.addWidget(self.changeUser)
        self.removeUser = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeUser.sizePolicy().hasHeightForWidth())
        self.removeUser.setSizePolicy(sizePolicy)
        self.removeUser.setMinimumSize(QtCore.QSize(75, 58))
        self.removeUser.setMaximumSize(QtCore.QSize(75, 58))
        self.removeUser.setObjectName("removeUser")
        self.horizontalLayout_19.addWidget(self.removeUser)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem8)
        self.verticalLayout_20.addLayout(self.horizontalLayout_19)
        self.verticalLayout_13.addLayout(self.verticalLayout_20)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setMinimumSize(QtCore.QSize(151, 41))
        self.label.setMaximumSize(QtCore.QSize(151, 41))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.week = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.week.sizePolicy().hasHeightForWidth())
        self.week.setSizePolicy(sizePolicy)
        self.week.setMinimumSize(QtCore.QSize(119, 39))
        self.week.setMaximumSize(QtCore.QSize(119, 39))
        self.week.setObjectName("week")
        self.horizontalLayout_5.addWidget(self.week)
        self.month = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.month.sizePolicy().hasHeightForWidth())
        self.month.setSizePolicy(sizePolicy)
        self.month.setMinimumSize(QtCore.QSize(119, 39))
        self.month.setMaximumSize(QtCore.QSize(119, 39))
        self.month.setObjectName("month")
        self.horizontalLayout_5.addWidget(self.month)
        self.year = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year.sizePolicy().hasHeightForWidth())
        self.year.setSizePolicy(sizePolicy)
        self.year.setMinimumSize(QtCore.QSize(119, 39))
        self.year.setMaximumSize(QtCore.QSize(119, 39))
        self.year.setObjectName("year")
        self.horizontalLayout_5.addWidget(self.year)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.yejiTable = QtWidgets.QTableView(self.tab_4)
        self.yejiTable.setMinimumSize(QtCore.QSize(911, 421))
        self.yejiTable.setObjectName("yejiTable")
        self.verticalLayout_10.addWidget(self.yejiTable)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.jiaoyiNumber = QtWidgets.QLabel(self.tab_4)
        self.jiaoyiNumber.setMinimumSize(QtCore.QSize(181, 32))
        self.jiaoyiNumber.setMaximumSize(QtCore.QSize(181, 32))
        self.jiaoyiNumber.setObjectName("jiaoyiNumber")
        self.verticalLayout_4.addWidget(self.jiaoyiNumber)
        self.jiaoyiPrice = QtWidgets.QLabel(self.tab_4)
        self.jiaoyiPrice.setMinimumSize(QtCore.QSize(181, 31))
        self.jiaoyiPrice.setMaximumSize(QtCore.QSize(181, 31))
        self.jiaoyiPrice.setObjectName("jiaoyiPrice")
        self.verticalLayout_4.addWidget(self.jiaoyiPrice)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.verticalLayout_14.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.shebeiTable = QtWidgets.QTableView(self.tab_5)
        self.shebeiTable.setMinimumSize(QtCore.QSize(941, 551))
        self.shebeiTable.setObjectName("shebeiTable")
        self.verticalLayout_2.addWidget(self.shebeiTable)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.start = QtWidgets.QPushButton(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        self.start.setMinimumSize(QtCore.QSize(75, 29))
        self.start.setMaximumSize(QtCore.QSize(75, 29))
        self.start.setObjectName("start")
        self.horizontalLayout_11.addWidget(self.start)
        self.stop = QtWidgets.QPushButton(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        self.stop.setMinimumSize(QtCore.QSize(75, 29))
        self.stop.setMaximumSize(QtCore.QSize(75, 29))
        self.stop.setObjectName("stop")
        self.horizontalLayout_11.addWidget(self.stop)
        self.refresh = QtWidgets.QPushButton(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh.sizePolicy().hasHeightForWidth())
        self.refresh.setSizePolicy(sizePolicy)
        self.refresh.setMinimumSize(QtCore.QSize(75, 29))
        self.refresh.setMaximumSize(QtCore.QSize(75, 29))
        self.refresh.setObjectName("refresh")
        self.horizontalLayout_11.addWidget(self.refresh)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout_15.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_5 = QtWidgets.QLabel(self.tab_7)
        self.label_5.setMinimumSize(QtCore.QSize(121, 31))
        self.label_5.setMaximumSize(QtCore.QSize(121, 31))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_16.addWidget(self.label_5)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem13)
        self.verticalLayout_19.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pcTable = QtWidgets.QTableView(self.tab_7)
        self.pcTable.setMinimumSize(QtCore.QSize(295, 214))
        self.pcTable.setMaximumSize(QtCore.QSize(16777215, 214))
        self.pcTable.setObjectName("pcTable")
        self.horizontalLayout_10.addWidget(self.pcTable)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.tab_7)
        self.label_7.setMinimumSize(QtCore.QSize(91, 165))
        self.label_7.setMaximumSize(QtCore.QSize(91, 165))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_16.addWidget(self.label_7)
        self.pcSave = QtWidgets.QPushButton(self.tab_7)
        self.pcSave.setMinimumSize(QtCore.QSize(91, 41))
        self.pcSave.setMaximumSize(QtCore.QSize(91, 41))
        self.pcSave.setObjectName("pcSave")
        self.verticalLayout_16.addWidget(self.pcSave)
        self.horizontalLayout_10.addLayout(self.verticalLayout_16)
        self.verticalLayout_19.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_15.addLayout(self.verticalLayout_19)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_3 = QtWidgets.QLabel(self.tab_7)
        self.label_3.setMinimumSize(QtCore.QSize(121, 31))
        self.label_3.setMaximumSize(QtCore.QSize(121, 31))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_14.addWidget(self.label_3)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem14)
        self.verticalLayout_21.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pwdTable = QtWidgets.QTableView(self.tab_7)
        self.pwdTable.setMinimumSize(QtCore.QSize(294, 214))
        self.pwdTable.setMaximumSize(QtCore.QSize(16777215, 214))
        self.pwdTable.setObjectName("pwdTable")
        self.horizontalLayout_12.addWidget(self.pwdTable)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_8 = QtWidgets.QLabel(self.tab_7)
        self.label_8.setMinimumSize(QtCore.QSize(91, 165))
        self.label_8.setMaximumSize(QtCore.QSize(91, 165))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_17.addWidget(self.label_8)
        self.pwdUpdate = QtWidgets.QPushButton(self.tab_7)
        self.pwdUpdate.setMinimumSize(QtCore.QSize(91, 41))
        self.pwdUpdate.setMaximumSize(QtCore.QSize(91, 41))
        self.pwdUpdate.setObjectName("pwdUpdate")
        self.verticalLayout_17.addWidget(self.pwdUpdate)
        self.horizontalLayout_12.addLayout(self.verticalLayout_17)
        self.verticalLayout_21.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15.addLayout(self.verticalLayout_21)
        self.verticalLayout_22.addLayout(self.horizontalLayout_15)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_4 = QtWidgets.QLabel(self.tab_7)
        self.label_4.setMinimumSize(QtCore.QSize(101, 31))
        self.label_4.setMaximumSize(QtCore.QSize(101, 31))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_18.addWidget(self.label_4)
        self.mendianTable = QtWidgets.QTableView(self.tab_7)
        self.mendianTable.setMinimumSize(QtCore.QSize(941, 311))
        self.mendianTable.setObjectName("mendianTable")
        self.verticalLayout_18.addWidget(self.mendianTable)
        self.verticalLayout_22.addLayout(self.verticalLayout_18)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tabWidget.addTab(self.tab_12, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "本店"))
        self.comboBox.setItemText(1, _translate("MainWindow", "全店"))
        self.label_10.setText(_translate("MainWindow", "---"))
        self.xiaofeiCheck.setText(_translate("MainWindow", "查询"))
        self.xiaofeiOut.setText(_translate("MainWindow", "导出"))
        self.xiaofeiIn.setText(_translate("MainWindow", "导入"))
        self.label_11.setText(_translate("MainWindow", "广州市聚义堂科技试用版"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("MainWindow", "门店消费"))
        self.menu1Add.setText(_translate("MainWindow", "新增"))
        self.menu1Update.setText(_translate("MainWindow", "修改"))
        self.menu1Remove.setText(_translate("MainWindow", "删除"))
        self.checkBox.setText(_translate("MainWindow", "品牌"))
        self.checkBox_2.setText(_translate("MainWindow", "型号"))
        self.checkBox_3.setText(_translate("MainWindow", "花纹"))
        self.checkBox_4.setText(_translate("MainWindow", "数量"))
        self.checkBox_5.setText(_translate("MainWindow", "单价"))
        self.checkBox_6.setText(_translate("MainWindow", "小记"))
        self.checkBox_7.setText(_translate("MainWindow", "工时费"))
        self.checkBox_8.setText(_translate("MainWindow", "总价"))
        self.checkBox_9.setText(_translate("MainWindow", "更换里程"))
        self.checkBox_10.setText(_translate("MainWindow", "备注"))
        self.checkBox_11.setText(_translate("MainWindow", "单位"))
        self.menu2Add.setText(_translate("MainWindow", "新增"))
        self.menu2Update.setText(_translate("MainWindow", "修改"))
        self.menu2Remove.setText(_translate("MainWindow", "删除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "门店服务"))
        self.userAdd.setText(_translate("MainWindow", "新增员工"))
        self.deleteWorker.setText(_translate("MainWindow", "删除"))
        self.updateWorker.setText(_translate("MainWindow", "修改"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "门店人员"))
        self.addUser.setText(_translate("MainWindow", "添加用户"))
        self.changeUser.setText(_translate("MainWindow", "修改用户"))
        self.removeUser.setText(_translate("MainWindow", "删除用户"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "用户管理"))
        self.week.setText(_translate("MainWindow", "本周"))
        self.month.setText(_translate("MainWindow", "本月"))
        self.year.setText(_translate("MainWindow", "本年"))
        self.jiaoyiNumber.setText(_translate("MainWindow", "总交易单数："))
        self.jiaoyiPrice.setText(_translate("MainWindow", "总交易金额："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "业绩报表"))
        self.start.setText(_translate("MainWindow", "启用"))
        self.stop.setText(_translate("MainWindow", "禁用"))
        self.refresh.setText(_translate("MainWindow", "刷新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "设备管理"))
        self.pcSave.setText(_translate("MainWindow", "保存"))
        self.label_3.setText(_translate("MainWindow", "修改最高权限密码"))
        self.pwdUpdate.setText(_translate("MainWindow", "保存"))
        self.label_4.setText(_translate("MainWindow", "所有门店信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "进货录入"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "进货管理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "库存查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "库存管理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "供应商对账"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("MainWindow", "经营顾问"))

