# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_performance.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(913, 596)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 913, 596))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(151, 41))
        self.label.setMaximumSize(QtCore.QSize(151, 41))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.today = QtWidgets.QPushButton(self.layoutWidget)
        self.today.setMinimumSize(QtCore.QSize(119, 39))
        self.today.setMaximumSize(QtCore.QSize(119, 39))
        self.today.setObjectName("today")
        self.horizontalLayout_5.addWidget(self.today)
        self.week = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.week.sizePolicy().hasHeightForWidth())
        self.week.setSizePolicy(sizePolicy)
        self.week.setMinimumSize(QtCore.QSize(119, 39))
        self.week.setMaximumSize(QtCore.QSize(119, 39))
        self.week.setObjectName("week")
        self.horizontalLayout_5.addWidget(self.week)
        self.month = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.month.sizePolicy().hasHeightForWidth())
        self.month.setSizePolicy(sizePolicy)
        self.month.setMinimumSize(QtCore.QSize(119, 39))
        self.month.setMaximumSize(QtCore.QSize(119, 39))
        self.month.setObjectName("month")
        self.horizontalLayout_5.addWidget(self.month)
        self.year = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year.sizePolicy().hasHeightForWidth())
        self.year.setSizePolicy(sizePolicy)
        self.year.setMinimumSize(QtCore.QSize(119, 39))
        self.year.setMaximumSize(QtCore.QSize(119, 39))
        self.year.setObjectName("year")
        self.horizontalLayout_5.addWidget(self.year)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.performance_table = QtWidgets.QTableView(self.layoutWidget)
        self.performance_table.setMinimumSize(QtCore.QSize(911, 391))
        self.performance_table.setObjectName("performance_table")
        self.performance_table.horizontalHeader().setStretchLastSection(True)
        self.performance_table.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.performance_table)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.deal_price = QtWidgets.QLabel(self.layoutWidget)
        self.deal_price.setMinimumSize(QtCore.QSize(181, 119))
        self.deal_price.setMaximumSize(QtCore.QSize(181, 119))
        self.deal_price.setObjectName("deal_price")
        self.horizontalLayout_6.addWidget(self.deal_price)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.today.setText(_translate("Form", "今日"))
        self.week.setText(_translate("Form", "本周"))
        self.month.setText(_translate("Form", "本月"))
        self.year.setText(_translate("Form", "本年"))
        self.deal_price.setText(_translate("Form", "     总交易单数：\n"
"\n"
"     总交易金额："))

