# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_sub_service_operation_data.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sub_serviceoperationdataForm(object):
    def setupUi(self, sub_serviceoperationdataForm):
        sub_serviceoperationdataForm.setObjectName("sub_serviceoperationdataForm")
        sub_serviceoperationdataForm.resize(880, 720)
        self.tableWidget = QtWidgets.QTableWidget(sub_serviceoperationdataForm)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 851, 601))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(sub_serviceoperationdataForm)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 731, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout.addWidget(self.dateTimeEdit)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.horizontalLayout.addWidget(self.dateTimeEdit_2)
        self.serchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.serchButton.setObjectName("serchButton")
        self.horizontalLayout.addWidget(self.serchButton)
        self.exportButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout.addWidget(self.exportButton)

        self.retranslateUi(sub_serviceoperationdataForm)
        QtCore.QMetaObject.connectSlotsByName(sub_serviceoperationdataForm)

    def retranslateUi(self, sub_serviceoperationdataForm):
        _translate = QtCore.QCoreApplication.translate
        sub_serviceoperationdataForm.setWindowTitle(_translate("sub_serviceoperationdataForm", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("sub_serviceoperationdataForm", "一级分类"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("sub_serviceoperationdataForm", "二级分类"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("sub_serviceoperationdataForm", "成交单量"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("sub_serviceoperationdataForm", "成交车次"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("sub_serviceoperationdataForm", "成交数量"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("sub_serviceoperationdataForm", "成交金额"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("sub_serviceoperationdataForm", "成交毛利"))
        self.label_3.setText(_translate("sub_serviceoperationdataForm", "选择门店"))
        self.label.setText(_translate("sub_serviceoperationdataForm", "起始时间"))
        self.label_2.setText(_translate("sub_serviceoperationdataForm", "结束时间"))
        self.serchButton.setText(_translate("sub_serviceoperationdataForm", "查询"))
        self.exportButton.setText(_translate("sub_serviceoperationdataForm", "导出"))

