# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_normal_stock_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(705, 499)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 10, 601, 431))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pinpailineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.pinpailineEdit.setObjectName("pinpailineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pinpailineEdit)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.xinghaolineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.xinghaolineEdit.setObjectName("xinghaolineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.xinghaolineEdit)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.shuolianglineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.shuolianglineEdit.setObjectName("shuolianglineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.shuolianglineEdit)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.danweilineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.danweilineEdit.setObjectName("danweilineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.danweilineEdit)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.danjialineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.danjialineEdit.setObjectName("danjialineEdit")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.danjialineEdit)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.xiaojilineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.xiaojilineEdit.setReadOnly(True)
        self.xiaojilineEdit.setObjectName("xiaojilineEdit")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.xiaojilineEdit)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.gongyingshanglineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.gongyingshanglineEdit.setObjectName("gongyingshanglineEdit")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.gongyingshanglineEdit)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.projectlineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.projectlineEdit.setObjectName("projectlineEdit")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.projectlineEdit)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.paylineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.paylineEdit.setReadOnly(True)
        self.paylineEdit.setObjectName("paylineEdit")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.paylineEdit)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.nopaylineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nopaylineEdit.setObjectName("nopaylineEdit")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.nopaylineEdit)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.methodlineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.methodlineEdit.setObjectName("methodlineEdit")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.methodlineEdit)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.notelineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.notelineEdit.setObjectName("notelineEdit")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.notelineEdit)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.commitButton = QtWidgets.QPushButton(Dialog)
        self.commitButton.setGeometry(QtCore.QRect(540, 450, 113, 32))
        self.commitButton.setObjectName("commitButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "进货日期"))
        self.label_2.setText(_translate("Dialog", "商品品牌"))
        self.label_3.setText(_translate("Dialog", "商品型号"))
        self.label_4.setText(_translate("Dialog", "进货数量"))
        self.label_5.setText(_translate("Dialog", "单位"))
        self.label_6.setText(_translate("Dialog", "进货单价"))
        self.label_8.setText(_translate("Dialog", "单品小计"))
        self.label_7.setText(_translate("Dialog", "供应商"))
        self.label_10.setText(_translate("Dialog", "所属项目"))
        self.label_9.setText(_translate("Dialog", "付款金额"))
        self.label_11.setText(_translate("Dialog", "未付金额"))
        self.label_12.setText(_translate("Dialog", "付款方式"))
        self.label_13.setText(_translate("Dialog", "备注"))
        self.dateTimeEdit.setDisplayFormat(_translate("Dialog", "yyyy/MM/dd HH:mm"))
        self.commitButton.setText(_translate("Dialog", "提交"))

