# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_stock_calibration_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_stock_calibrationDialog(object):
    def setupUi(self, stock_calibrationDialog):
        stock_calibrationDialog.setObjectName("stock_calibrationDialog")
        stock_calibrationDialog.resize(331, 374)
        stock_calibrationDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(stock_calibrationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(stock_calibrationDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.calibration_date = QtWidgets.QDateEdit(stock_calibrationDialog)
        self.calibration_date.setMinimumSize(QtCore.QSize(165, 26))
        self.calibration_date.setMaximumSize(QtCore.QSize(165, 26))
        self.calibration_date.setObjectName("calibration_date")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.calibration_date)
        self.label = QtWidgets.QLabel(stock_calibrationDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.brand_combo = QtWidgets.QComboBox(stock_calibrationDialog)
        self.brand_combo.setMinimumSize(QtCore.QSize(165, 26))
        self.brand_combo.setMaximumSize(QtCore.QSize(165, 26))
        self.brand_combo.setObjectName("brand_combo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.brand_combo)
        self.label_6 = QtWidgets.QLabel(stock_calibrationDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.model_combo = QtWidgets.QComboBox(stock_calibrationDialog)
        self.model_combo.setMinimumSize(QtCore.QSize(165, 26))
        self.model_combo.setMaximumSize(QtCore.QSize(165, 26))
        self.model_combo.setObjectName("model_combo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.model_combo)
        self.label_7 = QtWidgets.QLabel(stock_calibrationDialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.balance_in_db = QtWidgets.QLineEdit(stock_calibrationDialog)
        self.balance_in_db.setMinimumSize(QtCore.QSize(165, 0))
        self.balance_in_db.setMaximumSize(QtCore.QSize(165, 16777215))
        self.balance_in_db.setToolTipDuration(-1)
        self.balance_in_db.setReadOnly(True)
        self.balance_in_db.setObjectName("balance_in_db")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.balance_in_db)
        self.label_8 = QtWidgets.QLabel(stock_calibrationDialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.money_in_db = QtWidgets.QLineEdit(stock_calibrationDialog)
        self.money_in_db.setMinimumSize(QtCore.QSize(165, 0))
        self.money_in_db.setMaximumSize(QtCore.QSize(165, 16777215))
        self.money_in_db.setToolTipDuration(-1)
        self.money_in_db.setReadOnly(True)
        self.money_in_db.setObjectName("money_in_db")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.money_in_db)
        self.label_9 = QtWidgets.QLabel(stock_calibrationDialog)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.balance_changed = QtWidgets.QLineEdit(stock_calibrationDialog)
        self.balance_changed.setMinimumSize(QtCore.QSize(165, 26))
        self.balance_changed.setMaximumSize(QtCore.QSize(165, 26))
        self.balance_changed.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.balance_changed.setObjectName("balance_changed")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.balance_changed)
        self.label_5 = QtWidgets.QLabel(stock_calibrationDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.money_changed = QtWidgets.QLineEdit(stock_calibrationDialog)
        self.money_changed.setMinimumSize(QtCore.QSize(165, 26))
        self.money_changed.setMaximumSize(QtCore.QSize(165, 26))
        self.money_changed.setReadOnly(False)
        self.money_changed.setObjectName("money_changed")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.money_changed)
        self.label_4 = QtWidgets.QLabel(stock_calibrationDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.notes = QtWidgets.QLineEdit(stock_calibrationDialog)
        self.notes.setMinimumSize(QtCore.QSize(165, 26))
        self.notes.setMaximumSize(QtCore.QSize(165, 26))
        self.notes.setObjectName("notes")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.notes)
        self.label_3 = QtWidgets.QLabel(stock_calibrationDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.staffComb = QtWidgets.QComboBox(stock_calibrationDialog)
        self.staffComb.setMinimumSize(QtCore.QSize(165, 26))
        self.staffComb.setMaximumSize(QtCore.QSize(165, 26))
        self.staffComb.setObjectName("staffComb")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.staffComb)
        self.addButton = QtWidgets.QPushButton(stock_calibrationDialog)
        self.addButton.setMinimumSize(QtCore.QSize(120, 0))
        self.addButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.addButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.addButton.setCheckable(False)
        self.addButton.setAutoDefault(True)
        self.addButton.setFlat(False)
        self.addButton.setObjectName("addButton")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.addButton)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(stock_calibrationDialog)
        QtCore.QMetaObject.connectSlotsByName(stock_calibrationDialog)
        stock_calibrationDialog.setTabOrder(self.calibration_date, self.brand_combo)
        stock_calibrationDialog.setTabOrder(self.brand_combo, self.model_combo)
        stock_calibrationDialog.setTabOrder(self.model_combo, self.balance_changed)
        stock_calibrationDialog.setTabOrder(self.balance_changed, self.money_changed)
        stock_calibrationDialog.setTabOrder(self.money_changed, self.notes)
        stock_calibrationDialog.setTabOrder(self.notes, self.staffComb)
        stock_calibrationDialog.setTabOrder(self.staffComb, self.addButton)
        stock_calibrationDialog.setTabOrder(self.addButton, self.balance_in_db)
        stock_calibrationDialog.setTabOrder(self.balance_in_db, self.money_in_db)

    def retranslateUi(self, stock_calibrationDialog):
        _translate = QtCore.QCoreApplication.translate
        stock_calibrationDialog.setWindowTitle(_translate("stock_calibrationDialog", "Dialog"))
        self.label_2.setText(_translate("stock_calibrationDialog", "日期"))
        self.calibration_date.setDisplayFormat(_translate("stock_calibrationDialog", "yyyy/MM/dd"))
        self.label.setText(_translate("stock_calibrationDialog", "品牌"))
        self.label_6.setText(_translate("stock_calibrationDialog", "商品型号"))
        self.label_7.setText(_translate("stock_calibrationDialog", "现有数量"))
        self.label_8.setText(_translate("stock_calibrationDialog", "库存金额"))
        self.label_9.setText(_translate("stock_calibrationDialog", "调整后数量"))
        self.balance_changed.setPlaceholderText(_translate("stock_calibrationDialog", "请输入调整的数量"))
        self.label_5.setText(_translate("stock_calibrationDialog", "调整后金额"))
        self.money_changed.setPlaceholderText(_translate("stock_calibrationDialog", "请输入调整的数量"))
        self.label_4.setText(_translate("stock_calibrationDialog", "备注"))
        self.label_3.setText(_translate("stock_calibrationDialog", "经手人"))
        self.addButton.setText(_translate("stock_calibrationDialog", "确定"))

