# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_stock_calibration_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_stock_calibrationDialog(object):
    def setupUi(self, stock_calibrationDialog):
        stock_calibrationDialog.setObjectName("stock_calibrationDialog")
        stock_calibrationDialog.resize(304, 297)
        stock_calibrationDialog.setModal(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(stock_calibrationDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(stock_calibrationDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label = QtWidgets.QLabel(stock_calibrationDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_9 = QtWidgets.QLabel(stock_calibrationDialog)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.toal = QtWidgets.QLineEdit(stock_calibrationDialog)
        self.toal.setMinimumSize(QtCore.QSize(150, 26))
        self.toal.setMaximumSize(QtCore.QSize(150, 26))
        self.toal.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.toal.setObjectName("toal")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.toal)
        self.label_3 = QtWidgets.QLabel(stock_calibrationDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.staffComb = QtWidgets.QComboBox(stock_calibrationDialog)
        self.staffComb.setMinimumSize(QtCore.QSize(150, 26))
        self.staffComb.setMaximumSize(QtCore.QSize(160, 26))
        self.staffComb.setObjectName("staffComb")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.staffComb)
        self.label_5 = QtWidgets.QLabel(stock_calibrationDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.money = QtWidgets.QLineEdit(stock_calibrationDialog)
        self.money.setMinimumSize(QtCore.QSize(150, 26))
        self.money.setMaximumSize(QtCore.QSize(150, 26))
        self.money.setReadOnly(False)
        self.money.setObjectName("money")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.money)
        self.label_6 = QtWidgets.QLabel(stock_calibrationDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.brand_combo = QtWidgets.QComboBox(stock_calibrationDialog)
        self.brand_combo.setMinimumSize(QtCore.QSize(150, 26))
        self.brand_combo.setMaximumSize(QtCore.QSize(160, 26))
        self.brand_combo.setObjectName("brand_combo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.brand_combo)
        self.model_combo = QtWidgets.QComboBox(stock_calibrationDialog)
        self.model_combo.setMinimumSize(QtCore.QSize(150, 26))
        self.model_combo.setMaximumSize(QtCore.QSize(160, 26))
        self.model_combo.setObjectName("model_combo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.model_combo)
        self.label_4 = QtWidgets.QLabel(stock_calibrationDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.notes = QtWidgets.QLineEdit(stock_calibrationDialog)
        self.notes.setMinimumSize(QtCore.QSize(150, 26))
        self.notes.setMaximumSize(QtCore.QSize(150, 26))
        self.notes.setObjectName("notes")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.notes)
        self.addButton = QtWidgets.QPushButton(stock_calibrationDialog)
        self.addButton.setMinimumSize(QtCore.QSize(120, 0))
        self.addButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.addButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.addButton.setCheckable(False)
        self.addButton.setAutoDefault(True)
        self.addButton.setFlat(False)
        self.addButton.setObjectName("addButton")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.addButton)
        self.dateEdit = QtWidgets.QDateEdit(stock_calibrationDialog)
        self.dateEdit.setMinimumSize(QtCore.QSize(150, 26))
        self.dateEdit.setMaximumSize(QtCore.QSize(160, 26))
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.horizontalLayout.addLayout(self.formLayout)

        self.retranslateUi(stock_calibrationDialog)
        QtCore.QMetaObject.connectSlotsByName(stock_calibrationDialog)
        stock_calibrationDialog.setTabOrder(self.toal, self.money)
        stock_calibrationDialog.setTabOrder(self.money, self.staffComb)

    def retranslateUi(self, stock_calibrationDialog):
        _translate = QtCore.QCoreApplication.translate
        stock_calibrationDialog.setWindowTitle(_translate("stock_calibrationDialog", "Dialog"))
        self.label_2.setText(_translate("stock_calibrationDialog", "日期"))
        self.label.setText(_translate("stock_calibrationDialog", "品牌"))
        self.label_9.setText(_translate("stock_calibrationDialog", "调整数量"))
        self.label_3.setText(_translate("stock_calibrationDialog", "经手人"))
        self.label_5.setText(_translate("stock_calibrationDialog", "调整金额"))
        self.label_6.setText(_translate("stock_calibrationDialog", "商品型号"))
        self.label_4.setText(_translate("stock_calibrationDialog", "备注"))
        self.addButton.setText(_translate("stock_calibrationDialog", "确定"))
        self.dateEdit.setDisplayFormat(_translate("stock_calibrationDialog", "yyyy/MM/dd"))

