# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_stock_calibration.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_stock_calibration(object):
    def setupUi(self, stock_calibration):
        stock_calibration.setObjectName("stock_calibration")
        stock_calibration.resize(953, 603)
        self.verticalLayout = QtWidgets.QVBoxLayout(stock_calibration)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(stock_calibration)
        self.label_6.setMinimumSize(QtCore.QSize(60, 26))
        self.label_6.setMaximumSize(QtCore.QSize(60, 26))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.start_date = QtWidgets.QDateEdit(stock_calibration)
        self.start_date.setMinimumSize(QtCore.QSize(135, 26))
        self.start_date.setMaximumSize(QtCore.QSize(135, 26))
        self.start_date.setObjectName("start_date")
        self.horizontalLayout.addWidget(self.start_date)
        self.label_4 = QtWidgets.QLabel(stock_calibration)
        self.label_4.setMinimumSize(QtCore.QSize(60, 26))
        self.label_4.setMaximumSize(QtCore.QSize(60, 26))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.first_srv_combo = QtWidgets.QComboBox(stock_calibration)
        self.first_srv_combo.setMinimumSize(QtCore.QSize(135, 26))
        self.first_srv_combo.setMaximumSize(QtCore.QSize(135, 26))
        self.first_srv_combo.setObjectName("first_srv_combo")
        self.horizontalLayout.addWidget(self.first_srv_combo)
        self.label_2 = QtWidgets.QLabel(stock_calibration)
        self.label_2.setMinimumSize(QtCore.QSize(60, 26))
        self.label_2.setMaximumSize(QtCore.QSize(60, 26))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.brand = QtWidgets.QLineEdit(stock_calibration)
        self.brand.setMinimumSize(QtCore.QSize(135, 0))
        self.brand.setMaximumSize(QtCore.QSize(135, 26))
        self.brand.setObjectName("brand")
        self.horizontalLayout.addWidget(self.brand)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(stock_calibration)
        self.label_5.setMinimumSize(QtCore.QSize(60, 26))
        self.label_5.setMaximumSize(QtCore.QSize(60, 26))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.end_date = QtWidgets.QDateEdit(stock_calibration)
        self.end_date.setMinimumSize(QtCore.QSize(135, 26))
        self.end_date.setMaximumSize(QtCore.QSize(135, 26))
        self.end_date.setObjectName("end_date")
        self.horizontalLayout_2.addWidget(self.end_date)
        self.label_3 = QtWidgets.QLabel(stock_calibration)
        self.label_3.setMinimumSize(QtCore.QSize(60, 26))
        self.label_3.setMaximumSize(QtCore.QSize(60, 26))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.second_srv_combo = QtWidgets.QComboBox(stock_calibration)
        self.second_srv_combo.setMinimumSize(QtCore.QSize(135, 26))
        self.second_srv_combo.setMaximumSize(QtCore.QSize(135, 26))
        self.second_srv_combo.setObjectName("second_srv_combo")
        self.horizontalLayout_2.addWidget(self.second_srv_combo)
        self.label = QtWidgets.QLabel(stock_calibration)
        self.label.setMinimumSize(QtCore.QSize(60, 26))
        self.label.setMaximumSize(QtCore.QSize(60, 26))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.model = QtWidgets.QLineEdit(stock_calibration)
        self.model.setMinimumSize(QtCore.QSize(135, 0))
        self.model.setMaximumSize(QtCore.QSize(135, 26))
        self.model.setObjectName("model")
        self.horizontalLayout_2.addWidget(self.model)
        self.seachButton = QtWidgets.QPushButton(stock_calibration)
        self.seachButton.setMinimumSize(QtCore.QSize(90, 26))
        self.seachButton.setMaximumSize(QtCore.QSize(90, 26))
        self.seachButton.setObjectName("seachButton")
        self.horizontalLayout_2.addWidget(self.seachButton)
        self.calibrationButton = QtWidgets.QPushButton(stock_calibration)
        self.calibrationButton.setMinimumSize(QtCore.QSize(90, 26))
        self.calibrationButton.setMaximumSize(QtCore.QSize(90, 26))
        self.calibrationButton.setObjectName("calibrationButton")
        self.horizontalLayout_2.addWidget(self.calibrationButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.tableView = QtWidgets.QTableView(stock_calibration)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.tableView)

        self.retranslateUi(stock_calibration)
        QtCore.QMetaObject.connectSlotsByName(stock_calibration)

    def retranslateUi(self, stock_calibration):
        _translate = QtCore.QCoreApplication.translate
        stock_calibration.setWindowTitle(_translate("stock_calibration", "Form"))
        self.label_6.setText(_translate("stock_calibration", "起始时间"))
        self.start_date.setDisplayFormat(_translate("stock_calibration", "yyyy-MM-dd"))
        self.label_4.setText(_translate("stock_calibration", "一级分类"))
        self.label_2.setText(_translate("stock_calibration", "商品品牌"))
        self.label_5.setText(_translate("stock_calibration", "结束时间"))
        self.end_date.setDisplayFormat(_translate("stock_calibration", "yyyy-MM-dd"))
        self.label_3.setText(_translate("stock_calibration", "二级分类"))
        self.label.setText(_translate("stock_calibration", "商品型号"))
        self.seachButton.setText(_translate("stock_calibration", "查询"))
        self.calibrationButton.setText(_translate("stock_calibration", "校准"))

