# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_normal_buy_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(414, 528)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 10, 281, 487))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.first_service_combo_box = QtWidgets.QComboBox(self.formLayoutWidget)
        self.first_service_combo_box.setMinimumSize(QtCore.QSize(150, 26))
        self.first_service_combo_box.setMaximumSize(QtCore.QSize(160, 45))
        self.first_service_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.first_service_combo_box.setMinimumContentsLength(10)
        self.first_service_combo_box.setObjectName("first_service_combo_box")
        self.gridLayout.addWidget(self.first_service_combo_box, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 13, 0, 1, 1)
        self.pay_type = QtWidgets.QComboBox(self.formLayoutWidget)
        self.pay_type.setMinimumSize(QtCore.QSize(150, 26))
        self.pay_type.setMaximumSize(QtCore.QSize(160, 45))
        self.pay_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.pay_type.setMinimumContentsLength(10)
        self.pay_type.setObjectName("pay_type")
        self.gridLayout.addWidget(self.pay_type, 10, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.number = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.number.setMinimumSize(QtCore.QSize(150, 0))
        self.number.setMaximumSize(QtCore.QSize(160, 16777215))
        self.number.setSizeIncrement(QtCore.QSize(0, 0))
        self.number.setInputMethodHints(QtCore.Qt.ImhNone)
        self.number.setObjectName("number")
        self.gridLayout.addWidget(self.number, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.unit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.unit.setMinimumSize(QtCore.QSize(150, 0))
        self.unit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.unit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.unit.setObjectName("unit")
        self.gridLayout.addWidget(self.unit, 7, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.commitButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.commitButton.setObjectName("commitButton")
        self.gridLayout.addWidget(self.commitButton, 14, 1, 1, 1)
        self.notelineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.notelineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.notelineEdit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.notelineEdit.setObjectName("notelineEdit")
        self.gridLayout.addWidget(self.notelineEdit, 13, 1, 1, 1)
        self.buy_time = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.buy_time.setMinimumSize(QtCore.QSize(150, 0))
        self.buy_time.setMaximumSize(QtCore.QSize(160, 16777215))
        self.buy_time.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.buy_time.setObjectName("buy_time")
        self.gridLayout.addWidget(self.buy_time, 0, 1, 1, 1)
        self.unpaid = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.unpaid.setMinimumSize(QtCore.QSize(150, 0))
        self.unpaid.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.unpaid.setFont(font)
        self.unpaid.setInputMethodHints(QtCore.Qt.ImhNone)
        self.unpaid.setReadOnly(True)
        self.unpaid.setObjectName("unpaid")
        self.gridLayout.addWidget(self.unpaid, 12, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 12, 0, 1, 1)
        self.total = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.total.setEnabled(False)
        self.total.setMinimumSize(QtCore.QSize(150, 0))
        self.total.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.total.setFont(font)
        self.total.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.total.setReadOnly(True)
        self.total.setObjectName("total")
        self.gridLayout.addWidget(self.total, 9, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 11, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 1)
        self.paid = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.paid.setMinimumSize(QtCore.QSize(150, 0))
        self.paid.setMaximumSize(QtCore.QSize(160, 16777215))
        self.paid.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.paid.setReadOnly(False)
        self.paid.setObjectName("paid")
        self.gridLayout.addWidget(self.paid, 11, 1, 1, 1)
        self.supplier_combo_box = QtWidgets.QComboBox(self.formLayoutWidget)
        self.supplier_combo_box.setMinimumSize(QtCore.QSize(150, 26))
        self.supplier_combo_box.setMaximumSize(QtCore.QSize(160, 45))
        self.supplier_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.supplier_combo_box.setMinimumContentsLength(10)
        self.supplier_combo_box.setObjectName("supplier_combo_box")
        self.gridLayout.addWidget(self.supplier_combo_box, 3, 1, 1, 1)
        self.model_combo_box = QtWidgets.QComboBox(self.formLayoutWidget)
        self.model_combo_box.setMinimumSize(QtCore.QSize(150, 26))
        self.model_combo_box.setMaximumSize(QtCore.QSize(160, 26))
        self.model_combo_box.setBaseSize(QtCore.QSize(150, 26))
        self.model_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.model_combo_box.setMinimumContentsLength(10)
        self.model_combo_box.setObjectName("model_combo_box")
        self.gridLayout.addWidget(self.model_combo_box, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 10, 0, 1, 1)
        self.buy_price = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.buy_price.setMinimumSize(QtCore.QSize(150, 0))
        self.buy_price.setMaximumSize(QtCore.QSize(160, 16777215))
        self.buy_price.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.buy_price.setObjectName("buy_price")
        self.gridLayout.addWidget(self.buy_price, 8, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 0, 1, 1)
        self.brand_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.brand_comboBox.setMinimumSize(QtCore.QSize(150, 26))
        self.brand_comboBox.setMaximumSize(QtCore.QSize(160, 26))
        self.brand_comboBox.setBaseSize(QtCore.QSize(150, 26))
        self.brand_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.brand_comboBox.setMinimumContentsLength(10)
        self.brand_comboBox.setObjectName("brand_comboBox")
        self.gridLayout.addWidget(self.brand_comboBox, 1, 1, 1, 1)
        self.second_service_combo_box = QtWidgets.QComboBox(self.formLayoutWidget)
        self.second_service_combo_box.setMinimumSize(QtCore.QSize(150, 26))
        self.second_service_combo_box.setMaximumSize(QtCore.QSize(160, 45))
        self.second_service_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.second_service_combo_box.setMinimumContentsLength(10)
        self.second_service_combo_box.setObjectName("second_service_combo_box")
        self.gridLayout.addWidget(self.second_service_combo_box, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.supplier_combo_box.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.buy_time, self.brand_comboBox)
        Dialog.setTabOrder(self.brand_comboBox, self.model_combo_box)
        Dialog.setTabOrder(self.model_combo_box, self.supplier_combo_box)
        Dialog.setTabOrder(self.supplier_combo_box, self.first_service_combo_box)
        Dialog.setTabOrder(self.first_service_combo_box, self.second_service_combo_box)
        Dialog.setTabOrder(self.second_service_combo_box, self.number)
        Dialog.setTabOrder(self.number, self.unit)
        Dialog.setTabOrder(self.unit, self.buy_price)
        Dialog.setTabOrder(self.buy_price, self.total)
        Dialog.setTabOrder(self.total, self.pay_type)
        Dialog.setTabOrder(self.pay_type, self.paid)
        Dialog.setTabOrder(self.paid, self.unpaid)
        Dialog.setTabOrder(self.unpaid, self.notelineEdit)
        Dialog.setTabOrder(self.notelineEdit, self.commitButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "单位"))
        self.label_3.setText(_translate("Dialog", "商品型号"))
        self.label_13.setText(_translate("Dialog", "备注"))
        self.label_6.setText(_translate("Dialog", "进货单价"))
        self.label_10.setText(_translate("Dialog", "一级项目"))
        self.label_7.setText(_translate("Dialog", "供应商"))
        self.label_2.setText(_translate("Dialog", "商品品牌"))
        self.label_4.setText(_translate("Dialog", "进货数量"))
        self.commitButton.setText(_translate("Dialog", "提交"))
        self.buy_time.setDisplayFormat(_translate("Dialog", "yyyy/MM/dd"))
        self.label_11.setText(_translate("Dialog", "未付金额"))
        self.label_9.setText(_translate("Dialog", "付款金额"))
        self.label_8.setText(_translate("Dialog", "单品小计:"))
        self.label_12.setText(_translate("Dialog", "付款方式"))
        self.label_14.setText(_translate("Dialog", "二级项目"))
        self.label.setText(_translate("Dialog", "进货日期"))

