# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_normal_buy_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(697, 557)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 10, 601, 502))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.buy_time = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        self.buy_time.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.buy_time.setObjectName("buy_time")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.buy_time)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.brand_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.brand_comboBox.setMinimumSize(QtCore.QSize(150, 26))
        self.brand_comboBox.setMaximumSize(QtCore.QSize(160, 26))
        self.brand_comboBox.setBaseSize(QtCore.QSize(150, 26))
        self.brand_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.brand_comboBox.setMinimumContentsLength(10)
        self.brand_comboBox.setObjectName("brand_comboBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.brand_comboBox)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.model_combo_box = QtWidgets.QComboBox(self.formLayoutWidget)
        self.model_combo_box.setMinimumSize(QtCore.QSize(150, 26))
        self.model_combo_box.setMaximumSize(QtCore.QSize(160, 26))
        self.model_combo_box.setBaseSize(QtCore.QSize(150, 26))
        self.model_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.model_combo_box.setMinimumContentsLength(10)
        self.model_combo_box.setObjectName("model_combo_box")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.model_combo_box)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.number = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.number.setObjectName("number")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.number)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.unit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.unit.setObjectName("unit")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.unit)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.buy_price = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.buy_price.setObjectName("buy_price")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.buy_price)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.total = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.total.setReadOnly(True)
        self.total.setObjectName("total")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.total)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.supplier_combo_box = QtWidgets.QComboBox(self.formLayoutWidget)
        self.supplier_combo_box.setMinimumSize(QtCore.QSize(150, 26))
        self.supplier_combo_box.setMaximumSize(QtCore.QSize(160, 45))
        self.supplier_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.supplier_combo_box.setMinimumContentsLength(10)
        self.supplier_combo_box.setObjectName("supplier_combo_box")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.supplier_combo_box)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.first_service_combo_box = QtWidgets.QComboBox(self.formLayoutWidget)
        self.first_service_combo_box.setMinimumSize(QtCore.QSize(150, 26))
        self.first_service_combo_box.setMaximumSize(QtCore.QSize(160, 45))
        self.first_service_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.first_service_combo_box.setMinimumContentsLength(10)
        self.first_service_combo_box.setObjectName("first_service_combo_box")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.first_service_combo_box)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.second_service_combo_box = QtWidgets.QComboBox(self.formLayoutWidget)
        self.second_service_combo_box.setMinimumSize(QtCore.QSize(150, 26))
        self.second_service_combo_box.setMaximumSize(QtCore.QSize(160, 45))
        self.second_service_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.second_service_combo_box.setMinimumContentsLength(10)
        self.second_service_combo_box.setObjectName("second_service_combo_box")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.second_service_combo_box)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.need_pay = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.need_pay.setReadOnly(False)
        self.need_pay.setObjectName("need_pay")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.need_pay)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.nopay = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nopay.setReadOnly(True)
        self.nopay.setObjectName("nopay")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.nopay)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.pay_type = QtWidgets.QComboBox(self.formLayoutWidget)
        self.pay_type.setMinimumSize(QtCore.QSize(150, 26))
        self.pay_type.setMaximumSize(QtCore.QSize(160, 45))
        self.pay_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.pay_type.setMinimumContentsLength(10)
        self.pay_type.setObjectName("pay_type")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.pay_type)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.notelineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.notelineEdit.setObjectName("notelineEdit")
        self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.notelineEdit)
        self.commitButton = QtWidgets.QPushButton(Dialog)
        self.commitButton.setGeometry(QtCore.QRect(540, 460, 113, 32))
        self.commitButton.setObjectName("commitButton")

        self.retranslateUi(Dialog)
        self.supplier_combo_box.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "进货日期"))
        self.buy_time.setDisplayFormat(_translate("Dialog", "yyyy/MM/dd HH:mm"))
        self.label_2.setText(_translate("Dialog", "商品品牌"))
        self.label_3.setText(_translate("Dialog", "商品型号"))
        self.label_4.setText(_translate("Dialog", "进货数量"))
        self.label_5.setText(_translate("Dialog", "单位"))
        self.label_6.setText(_translate("Dialog", "进货单价"))
        self.label_8.setText(_translate("Dialog", "单品小计"))
        self.label_7.setText(_translate("Dialog", "供应商"))
        self.label_10.setText(_translate("Dialog", "所属一级项目"))
        self.label_14.setText(_translate("Dialog", "二级项目"))
        self.label_9.setText(_translate("Dialog", "付款金额"))
        self.label_11.setText(_translate("Dialog", "未付金额"))
        self.label_12.setText(_translate("Dialog", "付款方式"))
        self.label_13.setText(_translate("Dialog", "备注"))
        self.commitButton.setText(_translate("Dialog", "提交"))

