# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_write_off_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_writeOffDialog(object):
    def setupUi(self, writeOffDialog):
        writeOffDialog.setObjectName("writeOffDialog")
        writeOffDialog.resize(379, 644)
        self.formLayoutWidget = QtWidgets.QWidget(writeOffDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 10, 274, 584))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.second_service = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.second_service.setMinimumSize(QtCore.QSize(150, 26))
        self.second_service.setMaximumSize(QtCore.QSize(150, 26))
        self.second_service.setReadOnly(True)
        self.second_service.setObjectName("second_service")
        self.gridLayout.addWidget(self.second_service, 10, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.unpaid = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.unpaid.setMinimumSize(QtCore.QSize(150, 26))
        self.unpaid.setMaximumSize(QtCore.QSize(150, 26))
        self.unpaid.setReadOnly(True)
        self.unpaid.setObjectName("unpaid")
        self.gridLayout.addWidget(self.unpaid, 12, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 13, 0, 1, 1)
        self.unit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.unit.setMinimumSize(QtCore.QSize(150, 26))
        self.unit.setMaximumSize(QtCore.QSize(150, 26))
        self.unit.setReadOnly(True)
        self.unit.setObjectName("unit")
        self.gridLayout.addWidget(self.unit, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.brand = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.brand.setMinimumSize(QtCore.QSize(150, 26))
        self.brand.setMaximumSize(QtCore.QSize(150, 26))
        self.brand.setObjectName("brand")
        self.gridLayout.addWidget(self.brand, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.sold_number = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sold_number.setMinimumSize(QtCore.QSize(150, 26))
        self.sold_number.setMaximumSize(QtCore.QSize(150, 26))
        self.sold_number.setReadOnly(True)
        self.sold_number.setObjectName("sold_number")
        self.gridLayout.addWidget(self.sold_number, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.total = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.total.setMinimumSize(QtCore.QSize(150, 26))
        self.total.setMaximumSize(QtCore.QSize(150, 26))
        self.total.setReadOnly(True)
        self.total.setObjectName("total")
        self.gridLayout.addWidget(self.total, 7, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.buy_date = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.buy_date.setMinimumSize(QtCore.QSize(150, 26))
        self.buy_date.setMaximumSize(QtCore.QSize(150, 26))
        self.buy_date.setObjectName("buy_date")
        self.gridLayout.addWidget(self.buy_date, 0, 1, 1, 1)
        self.notes = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.notes.setMinimumSize(QtCore.QSize(150, 26))
        self.notes.setMaximumSize(QtCore.QSize(150, 26))
        self.notes.setObjectName("notes")
        self.gridLayout.addWidget(self.notes, 14, 1, 1, 1)
        self.model = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.model.setMinimumSize(QtCore.QSize(150, 26))
        self.model.setMaximumSize(QtCore.QSize(150, 26))
        self.model.setObjectName("model")
        self.gridLayout.addWidget(self.model, 2, 1, 1, 1)
        self.payment_method_combo = QtWidgets.QComboBox(self.formLayoutWidget)
        self.payment_method_combo.setMinimumSize(QtCore.QSize(150, 26))
        self.payment_method_combo.setMaximumSize(QtCore.QSize(160, 26))
        self.payment_method_combo.setObjectName("payment_method_combo")
        self.gridLayout.addWidget(self.payment_method_combo, 13, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.unit_price = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.unit_price.setMinimumSize(QtCore.QSize(150, 26))
        self.unit_price.setMaximumSize(QtCore.QSize(150, 26))
        self.unit_price.setReadOnly(False)
        self.unit_price.setObjectName("unit_price")
        self.gridLayout.addWidget(self.unit_price, 6, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.paid = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.paid.setMinimumSize(QtCore.QSize(150, 26))
        self.paid.setMaximumSize(QtCore.QSize(150, 26))
        self.paid.setReadOnly(False)
        self.paid.setObjectName("paid")
        self.gridLayout.addWidget(self.paid, 11, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 10, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 11, 0, 1, 1)
        self.first_service = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.first_service.setMinimumSize(QtCore.QSize(150, 26))
        self.first_service.setMaximumSize(QtCore.QSize(150, 26))
        self.first_service.setReadOnly(True)
        self.first_service.setObjectName("first_service")
        self.gridLayout.addWidget(self.first_service, 9, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 14, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 12, 0, 1, 1)
        self.supplier_combo = QtWidgets.QComboBox(self.formLayoutWidget)
        self.supplier_combo.setMinimumSize(QtCore.QSize(150, 26))
        self.supplier_combo.setMaximumSize(QtCore.QSize(160, 26))
        self.supplier_combo.setObjectName("supplier_combo")
        self.gridLayout.addWidget(self.supplier_combo, 8, 1, 1, 1)
        self.buy_number = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.buy_number.setMinimumSize(QtCore.QSize(150, 26))
        self.buy_number.setMaximumSize(QtCore.QSize(150, 16777215))
        self.buy_number.setObjectName("buy_number")
        self.gridLayout.addWidget(self.buy_number, 4, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(writeOffDialog)
        self.pushButton.setGeometry(QtCore.QRect(240, 600, 91, 32))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(writeOffDialog)
        QtCore.QMetaObject.connectSlotsByName(writeOffDialog)
        writeOffDialog.setTabOrder(self.buy_date, self.sold_number)
        writeOffDialog.setTabOrder(self.sold_number, self.unit)
        writeOffDialog.setTabOrder(self.unit, self.unit_price)
        writeOffDialog.setTabOrder(self.unit_price, self.total)
        writeOffDialog.setTabOrder(self.total, self.paid)
        writeOffDialog.setTabOrder(self.paid, self.unpaid)
        writeOffDialog.setTabOrder(self.unpaid, self.payment_method_combo)
        writeOffDialog.setTabOrder(self.payment_method_combo, self.notes)

    def retranslateUi(self, writeOffDialog):
        _translate = QtCore.QCoreApplication.translate
        writeOffDialog.setWindowTitle(_translate("writeOffDialog", "Dialog"))
        self.label_2.setText(_translate("writeOffDialog", "商品品牌"))
        self.label_12.setText(_translate("writeOffDialog", "付款方式"))
        self.label_3.setText(_translate("writeOffDialog", "商品型号"))
        self.label.setText(_translate("writeOffDialog", "进货日期"))
        self.label_5.setText(_translate("writeOffDialog", "单位"))
        self.label_6.setText(_translate("writeOffDialog", "进货单价"))
        self.label_8.setText(_translate("writeOffDialog", "单品小计"))
        self.buy_date.setDisplayFormat(_translate("writeOffDialog", "yyyy/MM/dd"))
        self.label_4.setText(_translate("writeOffDialog", "销售数量"))
        self.label_10.setText(_translate("writeOffDialog", "一级项目"))
        self.label_15.setText(_translate("writeOffDialog", "进货数量"))
        self.label_7.setText(_translate("writeOffDialog", "供应商"))
        self.label_14.setText(_translate("writeOffDialog", "二级项目"))
        self.label_9.setText(_translate("writeOffDialog", "付款金额"))
        self.label_13.setText(_translate("writeOffDialog", "备注"))
        self.label_11.setText(_translate("writeOffDialog", "未付金额"))
        self.pushButton.setText(_translate("writeOffDialog", "确定"))

