# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_write_off_query.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_writeOffForm(object):
    def setupUi(self, writeOffForm):
        writeOffForm.setObjectName("writeOffForm")
        writeOffForm.resize(953, 602)
        self.verticalLayout = QtWidgets.QVBoxLayout(writeOffForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.write_off_table = QtWidgets.QTableView(writeOffForm)
        self.write_off_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.write_off_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.write_off_table.setSortingEnabled(True)
        self.write_off_table.setObjectName("write_off_table")
        self.write_off_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.write_off_table)
        self.scrollArea = QtWidgets.QScrollArea(writeOffForm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1400, 145))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(1400, 0))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(1400, 16777215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setMinimumSize(QtCore.QSize(90, 28))
        self.label_2.setMaximumSize(QtCore.QSize(90, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setMinimumSize(QtCore.QSize(150, 28))
        self.label_14.setMaximumSize(QtCore.QSize(150, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setMinimumSize(QtCore.QSize(80, 28))
        self.label_13.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setMinimumSize(QtCore.QSize(80, 28))
        self.label_12.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setMinimumSize(QtCore.QSize(60, 28))
        self.label_11.setMaximumSize(QtCore.QSize(60, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setMinimumSize(QtCore.QSize(60, 28))
        self.label_10.setMaximumSize(QtCore.QSize(60, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setMinimumSize(QtCore.QSize(60, 28))
        self.label.setMaximumSize(QtCore.QSize(60, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setMinimumSize(QtCore.QSize(70, 28))
        self.label_9.setMaximumSize(QtCore.QSize(70, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setMinimumSize(QtCore.QSize(70, 28))
        self.label_8.setMaximumSize(QtCore.QSize(70, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setMinimumSize(QtCore.QSize(150, 28))
        self.label_7.setMaximumSize(QtCore.QSize(150, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setMinimumSize(QtCore.QSize(80, 28))
        self.label_6.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setMinimumSize(QtCore.QSize(80, 28))
        self.label_5.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setMinimumSize(QtCore.QSize(100, 28))
        self.label_4.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setMinimumSize(QtCore.QSize(100, 28))
        self.label_3.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buy_date = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.buy_date.setMinimumSize(QtCore.QSize(90, 28))
        self.buy_date.setMaximumSize(QtCore.QSize(90, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buy_date.setFont(font)
        self.buy_date.setDate(QtCore.QDate(2018, 1, 15))
        self.buy_date.setObjectName("buy_date")
        self.horizontalLayout_4.addWidget(self.buy_date)
        self.service = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.service.setMinimumSize(QtCore.QSize(150, 28))
        self.service.setMaximumSize(QtCore.QSize(150, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.service.setFont(font)
        self.service.setReadOnly(True)
        self.service.setObjectName("service")
        self.horizontalLayout_4.addWidget(self.service)
        self.brand = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.brand.setMinimumSize(QtCore.QSize(80, 28))
        self.brand.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.brand.setFont(font)
        self.brand.setObjectName("brand")
        self.horizontalLayout_4.addWidget(self.brand)
        self.model = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.model.setMinimumSize(QtCore.QSize(80, 28))
        self.model.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.model.setFont(font)
        self.model.setObjectName("model")
        self.horizontalLayout_4.addWidget(self.model)
        self.sale_number = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.sale_number.setMinimumSize(QtCore.QSize(60, 28))
        self.sale_number.setMaximumSize(QtCore.QSize(60, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sale_number.setFont(font)
        self.sale_number.setReadOnly(True)
        self.sale_number.setObjectName("sale_number")
        self.horizontalLayout_4.addWidget(self.sale_number)
        self.unit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.unit.setMinimumSize(QtCore.QSize(60, 28))
        self.unit.setMaximumSize(QtCore.QSize(60, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.unit.setFont(font)
        self.unit.setReadOnly(True)
        self.unit.setObjectName("unit")
        self.horizontalLayout_4.addWidget(self.unit)
        self.buy_number = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.buy_number.setMinimumSize(QtCore.QSize(60, 28))
        self.buy_number.setMaximumSize(QtCore.QSize(60, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buy_number.setFont(font)
        self.buy_number.setObjectName("buy_number")
        self.horizontalLayout_4.addWidget(self.buy_number)
        self.price = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.price.setMinimumSize(QtCore.QSize(70, 28))
        self.price.setMaximumSize(QtCore.QSize(70, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.price.setFont(font)
        self.price.setObjectName("price")
        self.horizontalLayout_4.addWidget(self.price)
        self.total = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.total.setMinimumSize(QtCore.QSize(70, 28))
        self.total.setMaximumSize(QtCore.QSize(70, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total.setFont(font)
        self.total.setReadOnly(True)
        self.total.setObjectName("total")
        self.horizontalLayout_4.addWidget(self.total)
        self.supplier = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.supplier.setMinimumSize(QtCore.QSize(150, 28))
        self.supplier.setMaximumSize(QtCore.QSize(150, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.supplier.setFont(font)
        self.supplier.setObjectName("supplier")
        self.horizontalLayout_4.addWidget(self.supplier)
        self.paid = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.paid.setMinimumSize(QtCore.QSize(80, 28))
        self.paid.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.paid.setFont(font)
        self.paid.setObjectName("paid")
        self.horizontalLayout_4.addWidget(self.paid)
        self.unpaid = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.unpaid.setMinimumSize(QtCore.QSize(80, 28))
        self.unpaid.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.unpaid.setFont(font)
        self.unpaid.setReadOnly(True)
        self.unpaid.setObjectName("unpaid")
        self.horizontalLayout_4.addWidget(self.unpaid)
        self.payment = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.payment.setMinimumSize(QtCore.QSize(100, 28))
        self.payment.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.payment.setFont(font)
        self.payment.setObjectName("payment")
        self.horizontalLayout_4.addWidget(self.payment)
        self.note = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.note.setMinimumSize(QtCore.QSize(100, 28))
        self.note.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.note.setFont(font)
        self.note.setObjectName("note")
        self.horizontalLayout_4.addWidget(self.note)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.writeOffButton = QtWidgets.QPushButton(writeOffForm)
        self.writeOffButton.setObjectName("writeOffButton")
        self.horizontalLayout.addWidget(self.writeOffButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(writeOffForm)
        QtCore.QMetaObject.connectSlotsByName(writeOffForm)
        writeOffForm.setTabOrder(self.write_off_table, self.scrollArea)
        writeOffForm.setTabOrder(self.scrollArea, self.buy_date)
        writeOffForm.setTabOrder(self.buy_date, self.service)
        writeOffForm.setTabOrder(self.service, self.brand)
        writeOffForm.setTabOrder(self.brand, self.model)
        writeOffForm.setTabOrder(self.model, self.sale_number)
        writeOffForm.setTabOrder(self.sale_number, self.unit)
        writeOffForm.setTabOrder(self.unit, self.buy_number)
        writeOffForm.setTabOrder(self.buy_number, self.price)
        writeOffForm.setTabOrder(self.price, self.total)
        writeOffForm.setTabOrder(self.total, self.supplier)
        writeOffForm.setTabOrder(self.supplier, self.paid)
        writeOffForm.setTabOrder(self.paid, self.unpaid)
        writeOffForm.setTabOrder(self.unpaid, self.payment)
        writeOffForm.setTabOrder(self.payment, self.note)
        writeOffForm.setTabOrder(self.note, self.writeOffButton)

    def retranslateUi(self, writeOffForm):
        _translate = QtCore.QCoreApplication.translate
        writeOffForm.setWindowTitle(_translate("writeOffForm", "销负信息"))
        self.label_2.setText(_translate("writeOffForm", "销售日期"))
        self.label_14.setText(_translate("writeOffForm", "所属项目"))
        self.label_13.setText(_translate("writeOffForm", "商品品牌"))
        self.label_12.setText(_translate("writeOffForm", "商品型号"))
        self.label_11.setText(_translate("writeOffForm", "销售数量"))
        self.label_10.setText(_translate("writeOffForm", "单位"))
        self.label.setText(_translate("writeOffForm", "进货数量"))
        self.label_9.setText(_translate("writeOffForm", "进货单价"))
        self.label_8.setText(_translate("writeOffForm", "单品小计"))
        self.label_7.setText(_translate("writeOffForm", "供应商"))
        self.label_6.setText(_translate("writeOffForm", "付款金额"))
        self.label_5.setText(_translate("writeOffForm", "未付金额"))
        self.label_4.setText(_translate("writeOffForm", "付款方式"))
        self.label_3.setText(_translate("writeOffForm", "备注"))
        self.buy_date.setDisplayFormat(_translate("writeOffForm", "yyyy-MM-dd"))
        self.writeOffButton.setText(_translate("writeOffForm", "销负"))

