# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_sale_detail.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SaleDetail(object):
    def setupUi(self, SaleDetail):
        SaleDetail.setObjectName("SaleDetail")
        SaleDetail.resize(961, 610)
        SaleDetail.setStyleSheet("")
        self.layoutWidget_2 = QtWidgets.QWidget(SaleDetail)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 962, 610))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.sales_details = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.sales_details.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.sales_details.setContentsMargins(0, 0, 0, 0)
        self.sales_details.setObjectName("sales_details")
        self.sales_details_query_statement = QtWidgets.QHBoxLayout()
        self.sales_details_query_statement.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.sales_details_query_statement.setContentsMargins(0, -1, -1, -1)
        self.sales_details_query_statement.setObjectName("sales_details_query_statement")
        self.start_end_date_lable = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_end_date_lable.setFont(font)
        self.start_end_date_lable.setIndent(8)
        self.start_end_date_lable.setObjectName("start_end_date_lable")
        self.sales_details_query_statement.addWidget(self.start_end_date_lable)
        self.start_date = QtWidgets.QDateEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_date.sizePolicy().hasHeightForWidth())
        self.start_date.setSizePolicy(sizePolicy)
        self.start_date.setMinimumSize(QtCore.QSize(88, 25))
        self.start_date.setMaximumSize(QtCore.QSize(88, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_date.setFont(font)
        self.start_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 1, 1), QtCore.QTime(0, 0, 0)))
        self.start_date.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.start_date.setDate(QtCore.QDate(2017, 1, 1))
        self.start_date.setObjectName("start_date")
        self.sales_details_query_statement.addWidget(self.start_date)
        self.hyphen = QtWidgets.QLabel(self.layoutWidget_2)
        self.hyphen.setObjectName("hyphen")
        self.sales_details_query_statement.addWidget(self.hyphen)
        self.end_date = QtWidgets.QDateEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_date.sizePolicy().hasHeightForWidth())
        self.end_date.setSizePolicy(sizePolicy)
        self.end_date.setMinimumSize(QtCore.QSize(88, 25))
        self.end_date.setMaximumSize(QtCore.QSize(88, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.end_date.setFont(font)
        self.end_date.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.end_date.setCalendarPopup(False)
        self.end_date.setDate(QtCore.QDate(2018, 1, 1))
        self.end_date.setObjectName("end_date")
        self.sales_details_query_statement.addWidget(self.end_date)
        self.details_query_button = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_query_button.sizePolicy().hasHeightForWidth())
        self.details_query_button.setSizePolicy(sizePolicy)
        self.details_query_button.setMinimumSize(QtCore.QSize(86, 30))
        self.details_query_button.setMaximumSize(QtCore.QSize(86, 30))
        self.details_query_button.setObjectName("details_query_button")
        self.sales_details_query_statement.addWidget(self.details_query_button)
        self.details_export_button = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_export_button.sizePolicy().hasHeightForWidth())
        self.details_export_button.setSizePolicy(sizePolicy)
        self.details_export_button.setMinimumSize(QtCore.QSize(85, 30))
        self.details_export_button.setMaximumSize(QtCore.QSize(86, 30))
        self.details_export_button.setObjectName("details_export_button")
        self.sales_details_query_statement.addWidget(self.details_export_button)
        self.details_import_button = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_import_button.sizePolicy().hasHeightForWidth())
        self.details_import_button.setSizePolicy(sizePolicy)
        self.details_import_button.setMinimumSize(QtCore.QSize(85, 30))
        self.details_import_button.setMaximumSize(QtCore.QSize(86, 30))
        self.details_import_button.setObjectName("details_import_button")
        self.sales_details_query_statement.addWidget(self.details_import_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sales_details_query_statement.addItem(spacerItem)
        self.sales_details.addLayout(self.sales_details_query_statement)
        self.sales_details_result_table = QtWidgets.QTableView(self.layoutWidget_2)
        self.sales_details_result_table.setMinimumSize(QtCore.QSize(950, 550))
        self.sales_details_result_table.setMaximumSize(QtCore.QSize(950, 550))
        self.sales_details_result_table.setAutoFillBackground(False)
        self.sales_details_result_table.setStyleSheet("margin-left:5px;\n"
"margin-right:5px;")
        self.sales_details_result_table.setObjectName("sales_details_result_table")
        self.sales_details.addWidget(self.sales_details_result_table)

        self.retranslateUi(SaleDetail)
        QtCore.QMetaObject.connectSlotsByName(SaleDetail)

    def retranslateUi(self, SaleDetail):
        _translate = QtCore.QCoreApplication.translate
        SaleDetail.setWindowTitle(_translate("SaleDetail", "Form"))
        self.start_end_date_lable.setText(_translate("SaleDetail", "起止时间："))
        self.start_date.setDisplayFormat(_translate("SaleDetail", "yyyy/MM/dd"))
        self.hyphen.setText(_translate("SaleDetail", "-"))
        self.end_date.setDisplayFormat(_translate("SaleDetail", "yyyy/MM/dd"))
        self.details_query_button.setText(_translate("SaleDetail", "查询"))
        self.details_export_button.setText(_translate("SaleDetail", "导出"))
        self.details_import_button.setText(_translate("SaleDetail", "导入"))

