# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(942, 573)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 815, 510))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(121, 31))
        self.label_5.setMaximumSize(QtCore.QSize(121, 31))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_16.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.verticalLayout_19.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pcTable = QtWidgets.QTableView(self.layoutWidget)
        self.pcTable.setMinimumSize(QtCore.QSize(295, 214))
        self.pcTable.setMaximumSize(QtCore.QSize(16777215, 214))
        self.pcTable.setObjectName("pcTable")
        self.horizontalLayout_10.addWidget(self.pcTable)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(91, 165))
        self.label_7.setMaximumSize(QtCore.QSize(91, 165))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_16.addWidget(self.label_7)
        self.pcSave = QtWidgets.QPushButton(self.layoutWidget)
        self.pcSave.setMinimumSize(QtCore.QSize(91, 41))
        self.pcSave.setMaximumSize(QtCore.QSize(91, 41))
        self.pcSave.setObjectName("pcSave")
        self.verticalLayout_16.addWidget(self.pcSave)
        self.horizontalLayout_10.addLayout(self.verticalLayout_16)
        self.verticalLayout_19.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_15.addLayout(self.verticalLayout_19)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(121, 31))
        self.label_3.setMaximumSize(QtCore.QSize(121, 31))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_14.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.verticalLayout_21.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pwdTable = QtWidgets.QTableView(self.layoutWidget)
        self.pwdTable.setMinimumSize(QtCore.QSize(294, 214))
        self.pwdTable.setMaximumSize(QtCore.QSize(16777215, 214))
        self.pwdTable.setObjectName("pwdTable")
        self.horizontalLayout_12.addWidget(self.pwdTable)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(91, 165))
        self.label_8.setMaximumSize(QtCore.QSize(91, 165))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_17.addWidget(self.label_8)
        self.pwdUpdate = QtWidgets.QPushButton(self.layoutWidget)
        self.pwdUpdate.setMinimumSize(QtCore.QSize(91, 41))
        self.pwdUpdate.setMaximumSize(QtCore.QSize(91, 41))
        self.pwdUpdate.setObjectName("pwdUpdate")
        self.verticalLayout_17.addWidget(self.pwdUpdate)
        self.horizontalLayout_12.addLayout(self.verticalLayout_17)
        self.verticalLayout_21.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15.addLayout(self.verticalLayout_21)
        self.mendianTable = QtWidgets.QTableView(Form)
        self.mendianTable.setGeometry(QtCore.QRect(0, 260, 941, 311))
        self.mendianTable.setMinimumSize(QtCore.QSize(941, 311))
        self.mendianTable.setObjectName("mendianTable")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "所有门店信息"))
        self.pcSave.setText(_translate("Form", "保存"))
        self.label_3.setText(_translate("Form", "修改最高权限密码"))
        self.pwdUpdate.setText(_translate("Form", "保存"))

