# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'service.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(970, 624)
        Form.setMinimumSize(QtCore.QSize(970, 600))
        Form.setMaximumSize(QtCore.QSize(982, 624))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menuOut = QtWidgets.QPushButton(Form)
        self.menuOut.setMinimumSize(QtCore.QSize(75, 31))
        self.menuOut.setMaximumSize(QtCore.QSize(75, 31))
        self.menuOut.setObjectName("menuOut")
        self.horizontalLayout_3.addWidget(self.menuOut)
        self.menuIn = QtWidgets.QPushButton(Form)
        self.menuIn.setMinimumSize(QtCore.QSize(75, 31))
        self.menuIn.setMaximumSize(QtCore.QSize(75, 31))
        self.menuIn.setObjectName("menuIn")
        self.horizontalLayout_3.addWidget(self.menuIn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.mendianMenu1 = QtWidgets.QTableView(Form)
        self.mendianMenu1.setMinimumSize(QtCore.QSize(470, 470))
        self.mendianMenu1.setMaximumSize(QtCore.QSize(470, 470))
        self.mendianMenu1.setObjectName("mendianMenu1")
        self.verticalLayout_7.addWidget(self.mendianMenu1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu1Add = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu1Add.sizePolicy().hasHeightForWidth())
        self.menu1Add.setSizePolicy(sizePolicy)
        self.menu1Add.setMinimumSize(QtCore.QSize(79, 42))
        self.menu1Add.setMaximumSize(QtCore.QSize(79, 42))
        self.menu1Add.setObjectName("menu1Add")
        self.horizontalLayout.addWidget(self.menu1Add)
        self.menu1Update = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu1Update.sizePolicy().hasHeightForWidth())
        self.menu1Update.setSizePolicy(sizePolicy)
        self.menu1Update.setMinimumSize(QtCore.QSize(79, 42))
        self.menu1Update.setMaximumSize(QtCore.QSize(79, 42))
        self.menu1Update.setObjectName("menu1Update")
        self.horizontalLayout.addWidget(self.menu1Update)
        self.menu1Remove = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu1Remove.sizePolicy().hasHeightForWidth())
        self.menu1Remove.setSizePolicy(sizePolicy)
        self.menu1Remove.setMinimumSize(QtCore.QSize(79, 42))
        self.menu1Remove.setMaximumSize(QtCore.QSize(79, 42))
        self.menu1Remove.setObjectName("menu1Remove")
        self.horizontalLayout.addWidget(self.menu1Remove)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mendianMenu2 = QtWidgets.QTableView(Form)
        self.mendianMenu2.setMinimumSize(QtCore.QSize(470, 470))
        self.mendianMenu2.setMaximumSize(QtCore.QSize(470, 470))
        self.mendianMenu2.setObjectName("mendianMenu2")
        self.verticalLayout_6.addWidget(self.mendianMenu2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.menu2Add = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu2Add.sizePolicy().hasHeightForWidth())
        self.menu2Add.setSizePolicy(sizePolicy)
        self.menu2Add.setMinimumSize(QtCore.QSize(75, 39))
        self.menu2Add.setMaximumSize(QtCore.QSize(75, 39))
        self.menu2Add.setObjectName("menu2Add")
        self.horizontalLayout_2.addWidget(self.menu2Add)
        self.menu2Update = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu2Update.sizePolicy().hasHeightForWidth())
        self.menu2Update.setSizePolicy(sizePolicy)
        self.menu2Update.setMinimumSize(QtCore.QSize(75, 39))
        self.menu2Update.setMaximumSize(QtCore.QSize(75, 39))
        self.menu2Update.setObjectName("menu2Update")
        self.horizontalLayout_2.addWidget(self.menu2Update)
        self.menu2Remove = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu2Remove.sizePolicy().hasHeightForWidth())
        self.menu2Remove.setSizePolicy(sizePolicy)
        self.menu2Remove.setMinimumSize(QtCore.QSize(75, 39))
        self.menu2Remove.setMaximumSize(QtCore.QSize(75, 39))
        self.menu2Remove.setObjectName("menu2Remove")
        self.horizontalLayout_2.addWidget(self.menu2Remove)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.menuOut.setText(_translate("Form", "导出"))
        self.menuIn.setText(_translate("Form", "导入"))
        self.menu1Add.setText(_translate("Form", "新增"))
        self.menu1Update.setText(_translate("Form", "修改"))
        self.menu1Remove.setText(_translate("Form", "删除"))
        self.menu2Add.setText(_translate("Form", "新增"))
        self.menu2Update.setText(_translate("Form", "修改"))
        self.menu2Remove.setText(_translate("Form", "删除"))

